### ISSUE TITLE
原神新聞 (zh-tw) 無法擷取最新分類的最新內容

### ISSUE THREAD

**Issue by TermSelf** [DIYgod/RSSHub#11336]
### 路由地址

```routes
/mihoyo/ys/:location?/:category?
```

### 完整路由地址

```fullroutes
/mihoyo/ys/zh-tw/latest
```

### 相关文档

https://docs.rsshub.app/game.html#mi-ha-you-yuan-shen

### 预期是什么？

擷取最新的內容

### 实际发生了什么？

擷取過期的內容

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
沒有錯誤訊息
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
/test
```routes
/mihoyo/ys/zh-tw/latest
```

**Comment by TonyRL** [comment]
Demo instance has no difficulties in obtaining the latest feed

<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/11386903/204339317-394d63df-429c-40dc-97c5-288227a901ce.png)
</details>

**Comment by TermSelf** [comment]
<details>
<summary>11/30</summary>

![](https://i.imgur.com/LoGvDvW.png)
</details>

**Comment by TermSelf** [comment]
<details>
<summary>12/05</summary>

![](https://i.imgur.com/o7QCLKG.png)
</details>

**Comment by TonyRL** [comment]
Looks like it's caused by differences in regional caching of the API.
<details>
<summary>HTTP header</summary>

![image](https://user-images.githubusercontent.com/11386903/206566621-b2a3350f-362e-4fae-ac3e-d6feba9f555d.png)
</details>

I've tested their API from different regions and obtained a similar result. Region B's result is more updated than region A's.
<details>
<summary>Region A</summary>

![image](https://user-images.githubusercontent.com/11386903/206567301-3e4a7d23-23d4-4dd0-a21b-ebbf49853857.png)
</details>

<details>
<summary>Region B</summary>

![image](https://user-images.githubusercontent.com/11386903/206567421-7c2d2a7c-539e-4b8c-85ae-4868cde8ef83.png)


</details>
