### ISSUE TITLE
知网部分期刊报错

### ISSUE THREAD

**Issue by fredericky123** [DIYgod/RSSHub#14585]
### 路由地址

```routes
/cnki/journals/debut/:name
```

### 完整路由地址

```fullroutes
https://rsshub.app/cnki/journals/debut/JJYJ
```

### 相关文档

https://docs.rsshub.app/routes/journal#zhong-guo-zhi-wang-wang-luo-shou-fa

### 预期是什么？

能订阅所有期刊的最新文章

### 实际发生了什么？

https://rsshub.app/cnki/journals/debut/JJYJ 报错而有的正常，如
https://rsshub.app/cnki/journals/debut/GLSJ

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
无
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
#12994

**Comment by fredericky123** [comment]
很奇怪，类似地
https://rsshub.app/hbr/topic/strategy 报错而
https://rsshub.app/hbr/topic/gender 正常

**Comment by Derekmini** [comment]
This is because the content of JJYJ's "网络首发(全部)" section is empty, which can be seen by comparing the content of GLSJ's "网络首发(全部)" section in the chart below:

_这是因为JJYJ的“网络首发(全部)”栏目内容为空，通过对比下图中GLSJ的“网络首发(全部)”栏目内容，可以看出来：_
<img width="500" alt="截屏2024-04-12 08 47 00" src="https://github.com/DIYgod/RSSHub/assets/30514323/d7379eba-f344-44fa-aaf5-b6147f718591">
<img width="500" alt="截屏2024-04-12 08 47 13" src="https://github.com/DIYgod/RSSHub/assets/30514323/aee4fa86-e69c-494b-aebd-d0ec0d9fef3b">

@TonyRL 
I kindly request that you close the issue. Additionally, I have updated the routing for `journals.ts` and `author.ts` related to CNKI, which will be submitted for CNKI PR after completing IEEE's PR.

_向您申请关闭该问题，另外关于知网的路由(journals & author)已经更新，即将在完成ieee的pr后，提交知网的pr。_

> 关键是同一个时间点https://rsshub.app/cnki/journals/debut/JJYJ 报错而 https://rsshub.app/cnki/journals/debut/GLSJ 正常 这是为啥呢
