### ISSUE TITLE
米游社重复推送

### ISSUE THREAD

**Issue by hirrao** [DIYgod/RSSHub#15558]
### 路由地址

```routes
/mihoyo/bbs/official/:gids/:type?/:page_size?/:last_id?
```

### 完整路由地址

```fullroutes
/mihoyo/bbs/official/6/1
```

### 相关文档

https://docs.rsshub.app/zh/routes/game#%E7%B1%B3%E6%B8%B8%E7%A4%BE-%E5%AE%98%E6%96%B9%E5%85%AC%E5%91%8A

### 预期是什么？

正常路由米游社公告

### 实际发生了什么？

间歇性来自星穹铁道的公告会在几天后由https://www.miyoushe.com/ys/article/XXX, 重新出现在路由中, 且不完整, 使用RSStt会进行多遍推送 比如https://www.miyoushe.com/sr/article/52432218
![image](https://github.com/DIYgod/RSSHub/assets/111119047/26af7530-6265-4c33-830a-3db4389227da)
在多天后重新以https://www.miyoushe.com/ys/article/52432218
![image](https://github.com/DIYgod/RSSHub/assets/111119047/dfd7dce3-b93f-4097-87d2-c10cff9c6c1f)
的形式再次进行推送, 此次推送图片和实际文本也都不具有, 发现重复推送后检查Rsshub生成的Rss(已经隔了一段时间, 缓存已经过期), 发现只有正常的那个Rss留存
长时间订阅该路由中的原神和星穹铁道, 从上个月底开始出现此类问题, 且仅有星穹铁道这个路由出现此类问题

### 部署

自建

### 部署相关信息

Debian 12  Docker 20.10.24

### 额外信息

```shell
Rsshub无报错
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by hirrao** [comment]
> ##### Searching for maintainers:
> * `/mihoyo/bbs/official/6/1`: **Route not found**
> 
> > To maintainers: if you are not willing to be disturbed, list your username in `scripts/workflow/test-issue/call-maintainer.js`. In this way, your username will be wrapped in an inline code block when tagged so you will not be notified.
> 
> If all routes can not be found, the issue will be closed automatically. Please use `NOROUTE` for a route-irrelevant issue or leave a comment if it is a mistake. 如果所有路由都无法匹配，issue 将会被自动关闭。如果 issue 和路由无关，请使用 `NOROUTE` 关键词，或者留下评论。我们会重新审核。

已修改路由

**Comment by Rongronggg9** [comment]
Wearing my RSStT hat, I am here to confirm that it is not a bug of RSStT.

The root cause of the issue is located here:

https://github.com/DIYgod/RSSHub/blob/5e8ea80a8ed9b1844c0efe79dc6fcd523c13ada5/lib/routes/mihoyo/bbs/official.ts#L76-L79
https://github.com/DIYgod/RSSHub/blob/5e8ea80a8ed9b1844c0efe79dc6fcd523c13ada5/lib/routes/mihoyo/bbs/official.ts#L89

When the `getPostFull` endpoint returns an error, these fallback values make the post empty and the `link` be `.../ys/...`. Since `guid` is filled with `link` in the route, the uniqueness of `guid` is gone.

Anyway, fixing the issue is quite easy and you'll see a PR later.
