### ISSUE TITLE
Abnormal error message

### ISSUE THREAD

**Issue by zhixideyu** [DIYgod/RSSHub#17369]
### 路由地址

```routes
/appstare/comments/:country/:appid
```

### 完整路由地址

```fullroutes
/appstare/comments/cn/989673964
```

### 相关文档

https://docs.rsshub.app/zh/routes/program-update#appstare

### 预期是什么？

Requesting this URL https://rsshub.app/appstare/comments/cn/989673964 should return data.

But it shows the error: FetchError: [GET] "https://monitor.appstare.net/spider/appComments?country=cn&appId=989673964": <no response> fetch failed.

In fact, accessing https://monitor.appstare.net/spider/appComments?country=cn&appId=989673964 directly returns data normally.

<img width="1414" alt="image" src="https://github.com/user-attachments/assets/c84fb034-81ed-4651-92aa-fb1f166d84d5">

### 实际发生了什么？

![WechatIMG2860](https://github.com/user-attachments/assets/009fe664-9440-4448-9e3d-14f8f70e75b0)

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
FetchError: [GET] "https://monitor.appstare.net/spider/appComments?country=cn&appId=989673964": <no response> fetch failed
```

### 这不是重复的 issue

- [X] 我已经搜索了 [现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by pseudoyu** [comment]
I can get expected response using my self-hosted instance via <https://rsshub.pseudoyu.com/appstare/comments/cn/989673964>.

May due to public instance's huge requests amount and the target website anti-crawler mechanism. It's recommended to deploy your own or try other public instance in <https://docs.rsshub.app/guide/instances>.
