### ISSUE TITLE
[RSS Request] Add Zaker channel Rss

### ISSUE THREAD

**Issue by DerekTso** [DIYgod/RSSHub#1851]
### Website URL
[http://www.myzaker.com/source/12291](http://www.myzaker.com/source/12291
)

### What content should be included?

- [ ] title
- [ ] content

**Comment by Wsine** [comment]
@DerekTso @DIYgod 
Could you please also add channel for zaker? The response page of 'channel' seems the same as that of 'source', so maybe it wouldn't be much work to deal with.

Since i am not familar with js and have no experiment environment, could i ask you two for a favor? 

## Website URL
http://www.myzaker.com/channel/13

## What content should be included?
- [ ] title
- [ ] content

## Additional description
