### ISSUE TITLE
半次元 RSS Wanted

### ISSUE THREAD

**Issue by DIYgod** [DIYgod/RSSHub#362]

**Comment by xyqfer** [comment]
@DIYgod 话说需要输出哪些内容 🌚

**Comment by DIYgod** [comment]
@xyqfer 我用的也比较少，大概是
- [ ] 热门
- [ ] 用户
- [ ] 标签
- [ ] 圈子

**Comment by xyqfer** [comment]
@DIYgod get(我用的也少 🌚

**Comment by SettingDust** [comment]
https://bcy.net/apiv3/common/hotTags
https://bcy.net/circle/timeline/loadtag?since=0&grid_type=timeline&tag_id=337549&sort=recent
https://bcy.net/home/timeline/loaduserposts?since=0&grid_type=timeline&uid=100419556750&limit=20
https://bcy.net/circle/timeline/showtag?since=26853.408&grid_type=flow&sort=hot&tag_id=72

**Comment by xfoxfu** [comment]
看起来目前并没有支持半次元，该功能是否仍需实现，或因为某些原因无法实现？

**Comment by yefoenix** [comment]
@xfoxfu 目前还没有人做，欢迎pr！
