### ISSUE TITLE
Instagram route returning "Error message: Unknown error"

### ISSUE THREAD

**Issue by igor-akhmetov** [DIYgod/RSSHub#6413]
- The involved route, with all required and optional parameters

Instagram route via my instance with correct Instagram credentials, e.g. myrsshub/instagram/user/airbus

- What is expected

The route return a feed.

- What is actually happening

I get an error:
Route requested: /instagram/user/airbus
Error message: Unknown error

- Self-deployment information

Latest docker image on my VPS host.

- Additional info (logs errors etc)

The log just contains "Unknown error" lines. It seems like after RSSHub is started the first Instagram route I request goes through and returns a feed, but after that the other Instagram route requests return the error.

**Comment by HenryQW** [comment]
The problem is the challenge prompted by Instagram when you log in on a new device. You will have to log in via Instagram app, click "this was me". If you do not do this, your subsequent login will likely be challenged by a security code, unfortunately it is very tricky to submit the code via your RSSHub. 

After clicking "this was me" 3 times, Instagram seems me remember my RSSHub and no longer causes the error.

**Comment by igor-akhmetov** [comment]
Thanks! That was my guess, I log on from my PC but got no confirmation prompt on the website. I guess I will try with the app.

**Comment by stjohnjohnson** [comment]
I'm still having the same issue.  I can load instagram for 2-3 users and then I get "unknown error."
