### ISSUE TITLE
推特路由部分失败，Error message: Unable to verify your credentials

### ISSUE THREAD

**Issue by dragon0629** [DIYgod/RSSHub#8642]
Looks like something went wrong
Route requested: /twitter/user/manu_manyu
Error message: Unable to verify your credentials
Helpful Information to provide when opening issue: 
Path: /twitter/user/manu_manyu
Node version: v16.3.0
        
如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        
在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.

目前有多个推特出现这个报错，但也不是全部
https://twitter.com/manu_manyu

请检查0_0

**Comment by shawn8888** [comment]
我用的是自建的twitter时间线路由。正常。
/twitter/followings/myuserid

**Comment by Mosney** [comment]
我也遇到了同样的问题，

https://rsshub.app/twitter/user/MiFwUpdater

上面这个路由会报错：
```
Helpful Information to provide when opening issue: 
Path: /twitter/user/MiFwUpdater
Node version: v16.3.0
```

测试了一下，任意改变大小写即有可能正常输出（比如把小写i改成大写I），但也有的组合不行（比如把大写U改成小写u），同样的字母大小写组合结果是固定正常或失败的，至少在我这里反复刷新结果是一样的，可能是命中了缓存（猜测是临时性拉取失败的结果也被缓存起来？）

**Comment by Rongronggg9** [comment]
> 我也遇到了同样的问题，
> 
> [rsshub.app/twitter/user/MiFwUpdater](https://rsshub.app/twitter/user/MiFwUpdater)
> 
> 上面这个路由会报错：
> 
> ```
> Helpful Information to provide when opening issue: 
> Path: /twitter/user/MiFwUpdater
> Node version: v16.3.0
> ```
> 
> 测试了一下，任意改变大小写即有可能正常输出（比如把小写i改成大写I），但也有的组合不行（比如把大写U改成小写u），同样的字母大小写组合结果是固定正常或失败的，至少在我这里反复刷新结果是一样的，可能是命中了缓存（猜测是临时性拉取失败的结果也被缓存起来？）

As for as I know, rsshub.app seems to have multiple instances and all of them are behind a load balancer. The error `Unable to verify your credentials` seems to occur from time to time but does not always occur. Maybe some of the instances are not configured properly? That's probably why changing the case of the username or changing the route parameters may help. IDK much since I am not a maintainer of the official instances.

CC @TonyRL @DIYgod 

Dupliacte #9423, #8650, #8865, #9463

**Comment by TonyRL** [comment]
Demo instances re-architected in August last year
