### ISSUE TITLE
#有新路由啦 无法使用

### ISSUE THREAD

**Issue by shengni** [DIYgod/RSSHub#8781]
### 路由地址

/rsshub/routes

### 完整路由地址

/rsshub/routes

### 相关文档

https://docs.rsshub.app/program-update.html#rsshub

### 预期是什么？

返回新的路由结果。

### 实际发生了什么？

Error message: cheerio is not a function

Helpful Information to provide when opening issue: 
Path: /rsshub/routes
Node version: v16.3.0

### 部署

RSSHub 演示 (https://rsshub.app)

### 额外信息

```shell
Error message: cheerio is not a function

Helpful Information to provide when opening issue: 
Path: /rsshub/routes
Node version: v16.3.0
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by TonyRL** [comment]
![wrong](https://user-images.githubusercontent.com/11386903/147415864-bb48e131-eef3-45cf-a641-6f2833b61c0b.png)

`/rsshub/routes` is working fine.

**Comment by qiaoyan** [comment]
Currently:

RSSHub
Looks like something went wrong

Route requested: /rsshub/routes

Error message: cheerio is not a function

Helpful Information to provide when opening issue: 
Path: /rsshub/routes
Node version: v16.3.0
        

如果您认为 RSSHub 导致了该错误，请在Github按照模版，复制本页面信息进行汇报
If you believe this is an error caused by RSSHub, please report on github
        

在线文档与支持，请访问docs.rsshub.app。

For online documentation and support please refer to docs.rsshub.app.
