### ISSUE TITLE
访问控制配置与Twitter选项不兼容

### ISSUE THREAD

**Issue by gouku** [DIYgod/RSSHub#9939]
### 路由地址

```routes
/twitter/user/:id/:routeParams?
```

### 完整路由地址

```fullroutes
/twitter/user/durov/count=2&key=123
```

### 相关文档

https://docs.rsshub.app/install/#pei-zhi-fang-wen-kong-zhi-pei-zhi

### 预期是什么？

以下形式可以正常访问：

- /twitter/user/durov/count=2&showEmojiForRetweetAndReply=1&key=123

### 实际发生了什么？

- /twitter/user/durov/count=2&showEmojiForRetweetAndReply=1&key=123 - 无法访问
- /twitter/user/durov/count=2&showEmojiForRetweetAndReply=1?key=123 - 正常访问

### 部署

自建

### 额外信息

```shell
这个两个参数组合在一起的时候，目前的配置是有点反直觉的，按照url的标准，第一个参数应该以 `?key=value`的形式开头，然后后面以`&key=value`的形式提供额外参数

根据rsshub的文档，如果要限制访问，很容易理解成`?key=xxx`放开头，然后把其他route的路由放后面，也就是下面的形式：

`/twitter/user/durov?key=123&count=5`

然而这时候是无法访问的，于是会尝试：

- `/twitter/user/durov?key=123/count=5`
- `/twitter/user/durov?count=5&key=123`
- `/twitter/user/durov/count=5&key=123`

发现都不可用，直到发现只有 `/twitter/user/durov/count=5?key=123`这种诡异的形式是“正确”的
```

### 这不是重复的 issue

- [X] 我已经搜索了[现有 issue](https://github.com/DIYgod/RSSHub/issues)，以确保该错误尚未被报告。

**Comment by Rongronggg9** [comment]
> 诡异的形式

https://en.wikipedia.org/wiki/Uniform_Resource_Identifier

Totally valid. Effectively distinguish **per route** options and **global** parameters. Not really an issue. 

```
https://example.com/hi/i/am/a/path/hello=i&am=a&part=of&the=path?cheers=i&am=a&query
```

**Comment by gouku** [comment]
> Totally valid

According to [rfc3986](https://datatracker.ietf.org/doc/html/rfc3986), yes. But why `/twitter/user/durov?key=123&count=5` is not valid? The documentation should be improved how to combine access key with route options.

> A nice book to kill one's time:

阴阳怪气？这书你读完了吗？

**Comment by TonyRL** [comment]
> But why /twitter/user/durov?key=123&count=5 is not valid?

It is also the reason why `/twitter/user/durov/count=5?key=123` works. `count` here is a route parameter that needs to be appeared in a route path which is handled through `ctx.params`
https://github.com/DIYgod/RSSHub/blob/303b91ffecb116d9c2315570c5d32234d89e5983/lib/routes/twitter/web-api/user.js#L8 Those key appears in the docs like `readable`, `authorNameBold`, etc. should use query string "liked" style instead of an actual query string(which comes after the delimiter `?`).

Meanwhile, the common parameter `key` is handled through `ctx.query` which needs to be passed in the query string in a URI.

After all, there is always room for improvement. But please be reminded that we believe everyone can act and interact in ways that contribute to an open, welcoming, diverse, inclusive, and healthy community as stated in our [Code of conduct](https://github.com/DIYgod/RSSHub/blob/master/CODE_OF_CONDUCT.md).

**Comment by NeverBehave** [comment]
https://github.com/DIYgod/RSSHub/discussions/9774

也许可以顺便考虑一下插件参数的prefixing，这样子的话这类问题会比较方便解决

**Comment by NeverBehave** [comment]
也许可以考虑一下给插件的参数直接做一个prefixing，透明处理的话可以在中间件直接去掉prefix传递出去

这样做的话也可以做到向后兼容（只处理检测到prefix的情况）
